Import the libereris 

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Import the dataSet 
turn into X and y



In [ ]:
data = pd.read_csv("heart.csv")
X = data.iloc[:,0:-1].values
y = data.iloc[:,-1].values
print(X)
print(y)

[[63.  1.  3. ...  0.  0.  1.]
 [37.  1.  2. ...  0.  0.  2.]
 [41.  0.  1. ...  2.  0.  2.]
 ...
 [68.  1.  0. ...  1.  2.  3.]
 [57.  1.  0. ...  1.  1.  3.]
 [57.  0.  1. ...  1.  1.  2.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


Clean the data:

*   replace missing slots or remove the entire row
*   transrfrom categorial data
*   one Hot encoding


Split into train and test

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

feature scailing


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

Create and train the model

KNN classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn_c = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_c.fit(X_train, y_train)

KNeighborsClassifier()

Classification tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree_c = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
tree_c.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

Random forest classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
forest_c = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
forest_c.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

Prediction:

*   single sample
*   x test



In [ ]:
y_pred_knn=knn_c.predict(X_test)
y_pred_tree=tree_c.predict(X_test)
y_pred_forest=forest_c.predict(X_test)

Test the results

In [ ]:
print(np.concatenate((y_pred_knn.reshape(len(y_pred_knn),1),y_pred_tree.reshape(len(y_pred_tree),1),y_pred_forest.reshape(len(y_pred_forest),1), y_test.reshape(len(y_test),1)),1))

[[0 0 0 0]
 [0 0 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [0 0 0 1]
 [1 1 1 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 0 1]
 [0 0 0 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 0 0 1]
 [1 1 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 1 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 0 1 1]
 [1 1 1 1]
 [0 0 1 0]
 [0 0 0 0]
 [1 1 1 1]
 [0 0 0 0]
 [1 0 0 0]
 [1 1 1 1]
 [1 0 0 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 0 1]
 [0 1 1 1]
 [1 1 1 1]
 [1 1 0 0]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 1]
 [0 1 1 1]
 [1 1 1 1]
 [1 0 1 1]
 [1 1 1 1]
 [0 0 0 0]
 [1 1 1 1]
 [1 1 1 0]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score
#cm = confusion_matrix(y_test, y_pred_knn)
#print(cm)
print("Knn accuracy is: "+str(accuracy_score(y_test, y_pred_knn)))
print("Tree accuracy is: "+str(accuracy_score(y_test, y_pred_tree)))
print("Forest accuracy is: "+str(accuracy_score(y_test, y_pred_forest)))

Knn accuracy is: 0.819672131147541
Tree accuracy is: 0.7868852459016393
Forest accuracy is: 0.8360655737704918
